// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_c67Y1O63HRMTGmIiBW9Os0R68D2o2Rk',
    appId: '1:1066893117610:web:7956a9ea0c40a6cc1628d3',
    messagingSenderId: '1066893117610',
    projectId: 'multipleacounts-3f14d',
    authDomain: 'multipleacounts-3f14d.firebaseapp.com',
    storageBucket: 'multipleacounts-3f14d.firebasestorage.app',
    measurementId: 'G-EMMNTMT2V5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqmBQO3mtdvpzbOZrOzjwnzCY1xn3-JXk',
    appId: '1:1066893117610:android:56ccd1d236d3802c1628d3',
    messagingSenderId: '1066893117610',
    projectId: 'multipleacounts-3f14d',
    storageBucket: 'multipleacounts-3f14d.firebasestorage.app',
  );
}
